[book]
title = "Computer Science and Game Design: The Comprehensive Pathway"
authors = ["Ryon Boswell"]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "docs"

[output.html]
additional-css = ["./theme/hints.css"]
additional-js = ["./theme/hints.js"]
no-section-label = true

[output.html.code.hidelines]
cpp = "~"

[output.html.fold]
enable = true
