[GPD1A]
hint = "Understand the basic game design elements, including conceptual ideas, storyline, visualization, storyboard, game effects, sound elements, game play, game controls, and player tutorial."

[GPD1B]
hint = "Create a design concept document."